# Generated by Django 4.1.3 on 2022-11-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huntapp", "0002_remove_influenceur_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="influenceur",
            name="photo",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
