# Generated by Django 4.1.3 on 2022-11-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arbre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[("French", "French"), ("English", "English")],
                        default="1",
                        max_length=20,
                    ),
                ),
                (
                    "experiment",
                    models.CharField(
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Intermediate", "Intermediate"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Man", "Man"), ("Women", "Women")],
                        default="1",
                        max_length=20,
                    ),
                ),
                (
                    "type_infl",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Beauty", "Beauty"),
                            ("Travel", "Travel"),
                            ("Lifestyle", "Lifestyle"),
                            ("High_Tech", "High_Tech"),
                            ("Sport", "Sport"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Influenceur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=1)),
                ("nationality", models.CharField(max_length=200)),
                ("nbr_followers", models.IntegerField(default=0)),
                ("theme", models.CharField(max_length=200)),
                ("experience", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=300)),
                ("photo", models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
